services:
  # Ollama service (run in Docker container)
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    restart: unless-stopped
    networks:
      - sc-network

  # Backend service
  backend:
    build: ./smart-copilot-backend
    ports:
      - "5050:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - OLLAMA_API_URL=http://ollama:11434
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=your_password_here
    env_file:
      - ./smart-copilot-backend/.env
    depends_on:
      - ollama
      - neo4j
    networks:
      - sc-network
    volumes:
      - ./smart-copilot-backend:/app

  # Frontend service
  frontend:
    build: ./smart-copilot-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - sc-network
    volumes:
      - ./smart-copilot-frontend:/app

  # Neo4j database service
  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"  # Web interface
      - "7687:7687"  # Bolt protocol
    environment:
      - NEO4J_AUTH=neo4j/your_password_here
    volumes:
      - neo4j-data:/data
    networks:
      - sc-network

# Volumes for persistent data
volumes:
  ollama-data:
  neo4j-data:

# Custom network for inter-container communication
networks:
  sc-network:
    driver: bridge

