services:
  # Ollama service (run in Docker container)
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - /Users/mibegerard/.ollama:/root/.ollama
    restart: unless-stopped
    networks:
      - sc-network

  # Backend service
  backend:
    build: ./smart-copilot-backend
    ports:
      - "5050:${PORT}"
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - OLLAMA_API_URL=${OLLAMA_API_URL}
      - NEO4J_URI=${NEO4J_URI}
      - NEO4J_USERNAME=${NEO4J_USERNAME}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
    env_file:
      - .env
    depends_on:
      - ollama
      - neo4j
    networks:
      - sc-network
    volumes:
      - ./smart-copilot-backend:/app

  # Frontend service
  frontend:
    build: ./smart-copilot-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - sc-network
    volumes:
      - ./smart-copilot-frontend:/app

  # Neo4j database service
  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"  # Web interface
      - "7687:7687"  # Bolt protocol
    environment:
      - NEO4J_AUTH=${NEO4J_USERNAME}/${NEO4J_PASSWORD}
    volumes:
      - neo4j-data:/data
    networks:
      - sc-network

# Volumes for persistent data
volumes:
  ollama-data:
  neo4j-data:

# Custom network for inter-container communication
networks:
  sc-network:
    driver: bridge